### ISSUE TITLE
Code duplicate with Line 120

### ISSUE THREAD

**Issue by sompornp** [dotnet-labs/ApiAuthDemo#1]
https://github.com/dotnet-labs/ApiAuthDemo/blob/909634bd553e9e039790a2cdceea0ea5b1a37dd8/ApiAuthDemo/Startup.cs#L133

**Comment by changhuixu** [comment]
Hi @b41somp 
Thank you for pointing it out. I guess you are pointing to an obsolete git Head. Could you clone the repo again or point the git Head to current branch? Thanks
